language: groovy
jdk:
  - oraclejdk8
install: ./gradlew resolveAllDependencies assemble
script: ./gradlew clean build
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
  - TERM=dumb
